sudo: required

language: c

services:
  - docker

os:
  - linux
  
global:
    - REPO=arvannginx
    - PROJECT_NAME=nginx
    - VERSION=1.15.8.1
    - FILE_NAME=${REPO}-${TRAVIS_TAG}.tar.gz

before_install:
  - sudo apt-get update
  - sudo apt-get install curl


script:
  - ROOT=$(pwd)
  - mkdir -p /tmp
  - mkdir -p /opt
  - mkdir -p /opt/openssl
  - curl -fsSL https://www.openssl.org/source/openssl-1.1.0j.tar.gz -o /tmp/openssl.tar.gz
  - tar -C /opt/openssl -xzf /tmp/openssl.tar.gz --strip-components 1
  - cd /opt/openssl
  - ls 
  - ./config
  - sudo make 1> /dev/null
  - sudo make install_sw 1> /dev/null
  - sudo ldconfig
  - cd $ROOT
  - ./auto/configure
  - make

before_deploy:
  - tar -czvf "${FILE_NAME}" auto/ conf/ contrib/ docs/ misc/ src/ .hgtags 

deploy:
  provider: releases
  api_key:
    secure: d98b299aaed3bb356463e8cc14aaea8e2f691198
  file: "${FILE_NAME}"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
