sudo: required

language: c

services:
  - docker

os:
  - linux
  
global:
    - PROJECT_NAME=nginx
    - VERSION=1.15.8.1
    - FILE_NAME=${PROJECT_NAME}-${VERSION}.tar.gz

before_install:
  - sudo apt-get update
  - sudo apt-get install curl


script:
  - ROOT=$(pwd)
  - mkdir -p /tmp
  - mkdir -p /opt
  - mkdir -p /opt/openssl
  - curl -fsSL https://www.openssl.org/source/openssl-1.1.0j.tar.gz -o /tmp/openssl.tar.gz
  - tar -C /opt/openssl -xzf /tmp/openssl.tar.gz --strip-components 1
  - cd /opt/openssl
  - ls 
  - ./config
  - sudo make 1> /dev/null
  - sudo make install_sw 1> /dev/null
  - sudo ldconfig
  - cd $ROOT
  - ./auto/configure --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy             --http-scgi-temp-path=/var/lib/nginx/scgi            --http-uwsgi-temp-path=/var/lib/nginx/uwsgi            --with-openssl-opt=enable-ec_nistp_64_gcc_128            --with-openssl-opt=no-nextprotoneg            --with-openssl-opt=no-weak-ssl-ciphers            --with-pcre-jit            --with-compat          --with-file-aio            --with-threads            --with-http_addition_module            --with-http_dav_module            --with-http_flv_module            --with-http_gunzip_module            --with-http_gzip_static_module            --with-http_mp4_module            --with-http_random_index_module            --with-http_realip_module            --with-http_slice_module            --with-http_ssl_module            --with-http_sub_module            --with-http_stub_status_module            --with-http_v2_module            --with-http_secure_link_module            --with-mail            --with-mail_ssl_module            --with-stream            --with-stream_realip_module            --with-stream_ssl_module            --with-stream_ssl_preread_module            --with-debug            --with-cc-opt='-g -O0 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2'            --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now'
  - make
deploy:
  provider: releases
  api_key:
    secure: d98b299aaed3bb356463e8cc14aaea8e2f691198
  file: "${FILE_NAME}"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
